# action.yml
name: Octave-UnitTests
description: Action for using Octave for testing Matlab unit tests
inputs:
  test_case:
    description: the name of the test class
    required: true
  directory:
    description: the directory where the test classes are defined in
    required: false
    default: .
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.test_case }}
    - ${{ inputs.directory }}
branding:
  icon: code
  color: orange
